### PR TITLE
Update to remove Opaque type and fix on nightly

### PR DESCRIPTION
**Pull request by djmcgill**

### CODE REVIEW

**Comment by djmcgill** [comment]
Fixes issue https://github.com/jmcomets/tcmalloc-rs/issues/1
The Opaque type was removed: https://github.com/rust-lang/rust/issues/49668#issuecomment-393263510

**Comment by jmcomets** [comment]
Thanks!

**Comment by ZhangHanDong** [comment]
@jmcomets  can u push a new version to crates.io ?

**Comment by jmcomets** [comment]
I just published version 0.1.5, should be good now :+1:

**Comment by jmcomets** [comment]
Also note that I pushed version 0.2.0, which requires Rust 1.28+, but works with stable.

**Comment by ZhangHanDong** [comment]
@jmcomets ok, thanks

**Pull request merged**
